/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nenanhjpeg;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author luongtopp
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    private String selectedImagePath;
    private BufferedImage bitmapImage = null;
    private JFileChooser browseImageFile = new JFileChooser("//Users//luongtopp//Desktop//");

    public Home() {
        initComponents();
        btnNen.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        imgAnhGoc = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        imgAnhNen = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        lblDoPhanGiai = new javax.swing.JLabel();
        lblDungLuong = new javax.swing.JLabel();
        lblDinhDang = new javax.swing.JLabel();
        lblBitsMau = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lblDoPhanGiai2 = new javax.swing.JLabel();
        lblDungLuong2 = new javax.swing.JLabel();
        lblDinhDang2 = new javax.swing.JLabel();
        lblBitsMau2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnChonAnh = new javax.swing.JButton();
        btnNen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ảnh gốc\n"));
        jPanel5.setLayout(new java.awt.BorderLayout());
        jPanel5.add(imgAnhGoc, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Ảnh nén"));
        jPanel6.setLayout(new java.awt.BorderLayout());
        jPanel6.add(imgAnhNen, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout());

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin ảnh gốc"));

        lblDoPhanGiai.setText("Độ phân giải:");

        lblDungLuong.setText("Dung lượng:");

        lblDinhDang.setText("Định dạng:");

        lblBitsMau.setText("Bits màu:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDoPhanGiai)
                    .addComponent(lblDungLuong)
                    .addComponent(lblDinhDang)
                    .addComponent(lblBitsMau))
                .addContainerGap(373, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblDoPhanGiai)
                .addGap(18, 18, 18)
                .addComponent(lblDungLuong)
                .addGap(18, 18, 18)
                .addComponent(lblDinhDang)
                .addGap(18, 18, 18)
                .addComponent(lblBitsMau)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel8);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin ảnh nén"));

        lblDoPhanGiai2.setText("Độ phân giải:");

        lblDungLuong2.setText("Dung lượng:");

        lblDinhDang2.setText("Định dạng:");

        lblBitsMau2.setText("Bits màu:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDoPhanGiai2)
                    .addComponent(lblDungLuong2)
                    .addComponent(lblDinhDang2)
                    .addComponent(lblBitsMau2))
                .addContainerGap(373, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblDoPhanGiai2)
                .addGap(18, 18, 18)
                .addComponent(lblDungLuong2)
                .addGap(18, 18, 18)
                .addComponent(lblDinhDang2)
                .addGap(18, 18, 18)
                .addComponent(lblBitsMau2)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel9);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        btnChonAnh.setText("Chọn ảnh");
        btnChonAnh.setMaximumSize(new java.awt.Dimension(104, 29));
        btnChonAnh.setMinimumSize(new java.awt.Dimension(104, 29));
        btnChonAnh.setPreferredSize(new java.awt.Dimension(104, 29));
        btnChonAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonAnhActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel2.add(btnChonAnh, gridBagConstraints);

        btnNen.setText("Nén");
        btnNen.setMaximumSize(new java.awt.Dimension(104, 29));
        btnNen.setMinimumSize(new java.awt.Dimension(104, 29));
        btnNen.setPreferredSize(new java.awt.Dimension(104, 29));
        btnNen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNenActionPerformed(evt);
            }
        });
        jPanel2.add(btnNen, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 951, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 951, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 541, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(119, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChonAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonAnhActionPerformed

        //Filter image extensions
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg", "bmp");
        browseImageFile.addChoosableFileFilter(fnef);
        int showOpenDialogue = browseImageFile.showOpenDialog(null);

        if (showOpenDialogue == JFileChooser.APPROVE_OPTION) {
            btnNen.setEnabled(true);

            File selectedImageFile = browseImageFile.getSelectedFile();
            selectedImagePath = selectedImageFile.getAbsolutePath();
            try {
                bitmapImage = ImageIO.read(new File(selectedImagePath));

            } catch (IOException e) {
                e.printStackTrace();
            }
            //Display image on jlable
            ImageIcon ii = new ImageIcon(bitmapImage);

//            / Lấy kích thước hiện thời của ảnh
            int imageWidth = ii.getIconWidth();
            int imageHeight = ii.getIconHeight();
            DecimalFormat decimalFormat = new DecimalFormat("#,###");
            lblDoPhanGiai.setText("Độ phân giải: " + imageWidth + " x " + imageHeight);
            String formatName;
            try {
                formatName = ImageIO.getImageReadersByFormatName(getFileExtension(selectedImageFile)).next().getFormatName();
                lblDinhDang.setText("Định dạng: " + formatName);
            } catch (IOException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
            String formattedNumber = decimalFormat.format(selectedImageFile.length());
            lblDungLuong.setText("Dung lượng: " + formattedNumber + " MB");
            lblBitsMau.setText("Bit màu: " + bitmapImage.getColorModel().getPixelSize());

            // Đặt kích thước muốn hiển thị của ảnh
            int desiredWidth = 298;
            int desiredHeight = 187;
            // Đọc tấm ảnh bitmap vào BufferedImage

            // Tính toán tỷ lệ để thay đổi kích thước của ảnh
            double widthRatio = (double) desiredWidth / imageWidth;
            double heightRatio = (double) desiredHeight / imageHeight;
            double scaleFactor = Math.min(widthRatio, heightRatio);

            // Thay đổi kích thước ảnh theo tỷ lệ
            int scaledWidth = (int) (imageWidth * scaleFactor);
            int scaledHeight = (int) (imageHeight * scaleFactor);
            Image scaledImage = ii.getImage().getScaledInstance(scaledWidth, scaledHeight, Image.SCALE_SMOOTH);

            // Tạo một ImageIcon mới từ ảnh đã thay đổi kích thước
            ImageIcon scaledImageIcon = new ImageIcon(scaledImage);

            // Đặt ảnh vào label
            imgAnhGoc.setIcon(scaledImageIcon);

            // Đặt kích thước cho label
            imgAnhGoc.setPreferredSize(new Dimension(desiredWidth, desiredHeight));

        }


    }//GEN-LAST:event_btnChonAnhActionPerformed

    private void btnNenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNenActionPerformed

        compressImage();

    }//GEN-LAST:event_btnNenActionPerformed
    private void compressImage() {
        // Chọn tệp ảnh BMP để nén
        DecimalFormat decimalFormat = new DecimalFormat("#,###");

        int result = browseImageFile.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File inputFile = browseImageFile.getSelectedFile();

            try {

                // Tạo tệp ảnh đầu ra với định dạng JPG
                String outputFilePath = inputFile.getAbsolutePath().replace(".bmp", ".jpg");
                File outputFile = new File(outputFilePath);
                ImageIO.write(bitmapImage, "jpg", outputFile);
                ImageIcon imageIcon = new ImageIcon(outputFilePath);
                int imageWidth = imageIcon.getIconWidth();
                int imageHeight = imageIcon.getIconHeight();
                // Lấy ảnh từ ImageIcon
                Image image = imageIcon.getImage();
                // Chỉ định kích thước mới cho ảnh
                // Đặt kích thước muốn hiển thị của ảnh
                int desiredWidth = 298;
                int desiredHeight = 187;
                // Đọc tấm ảnh bitmap vào BufferedImage

                // Tính toán tỷ lệ để thay đổi kích thước của ảnh
                double widthRatio = (double) desiredWidth / imageWidth;
                double heightRatio = (double) desiredHeight / imageHeight;
                double scaleFactor = Math.min(widthRatio, heightRatio);

                // Thay đổi kích thước ảnh theo tỷ lệ
                int scaledWidth = (int) (imageWidth * scaleFactor);
                int scaledHeight = (int) (imageHeight * scaleFactor);
                Image scaledImage = imageIcon.getImage().getScaledInstance(scaledWidth, scaledHeight, Image.SCALE_SMOOTH);

                // Tạo một ImageIcon mới từ ảnh đã được chỉnh kích thước
                ImageIcon resizedIcon = new ImageIcon(scaledImage);
                imgAnhNen.setIcon(resizedIcon);
                // Hiển thị thông tin về ảnh đã nén
                int compressedWidth = bitmapImage.getWidth();
                int compressedHeight = bitmapImage.getHeight();
                long compressedFileSize = outputFile.length();

                lblDoPhanGiai2.setText("Độ phân giải: " + compressedWidth + " x " + compressedHeight);
                String formatName;
                try {
                    formatName = ImageIO.getImageReadersByFormatName(getFileExtension(outputFile)).next().getFormatName();
                    lblDinhDang2.setText("Định dạng: " + formatName);
                } catch (IOException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
                String formattedNumber = decimalFormat.format(compressedFileSize);
                lblDungLuong2.setText("Dung lượng: " + formattedNumber + " MB");
                lblBitsMau2.setText("Bit màu: " + bitmapImage.getColorModel().getPixelSize());
                btnNen.setEnabled(false);

            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    private static String getFileExtension(File file) {
        String fileName = file.getName();
        int dotIndex = fileName.lastIndexOf(".");
        if (dotIndex != -1 && dotIndex < fileName.length() - 1) {
            return fileName.substring(dotIndex + 1);
        }
        return "";
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonAnh;
    private javax.swing.JButton btnNen;
    private javax.swing.JLabel imgAnhGoc;
    private javax.swing.JLabel imgAnhNen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblBitsMau;
    private javax.swing.JLabel lblBitsMau2;
    private javax.swing.JLabel lblDinhDang;
    private javax.swing.JLabel lblDinhDang2;
    private javax.swing.JLabel lblDoPhanGiai;
    private javax.swing.JLabel lblDoPhanGiai2;
    private javax.swing.JLabel lblDungLuong;
    private javax.swing.JLabel lblDungLuong2;
    // End of variables declaration//GEN-END:variables
}
